modLoader="javafml"
loaderVersion="${forge_version_range}"
license="https://github.com/JimiIT92/Mineworld/blob/master/LICENSE"
issueTrackerURL="https://github.com/JimiIT92/MineWorld/issues"
[[mods]]
modId="mineworld"
version="${file.jarVersion}"
displayName="MineWorld"
updateJSONURL="https://raw.githubusercontent.com/JimiIT92/MineWorld/master/version/update.json"
displayURL="https://mineworldminecraft.altervista.org/"
logoFile="MineWorld.png"
credits='''

Thanks to everyone that contributed through the years
and supported the project.

The full credits list can be found here:
https://github.com/JimiIT92/Mineworld/blob/master/CREDITS.md
'''
authors="JimiIT92"
displayTest="MATCH_VERSION"
description="Just another Minecraft mod"
[[dependencies.mineworld]]
   modId="terrablender"
   mandatory=true
   versionRange="[${mc_version}-${terrablender_version},)"
   ordering="NONE"
   side="BOTH"
[[dependencies.mineworld]]
   modId="jei"
   mandatory=false
   versionRange="[${mc_version}-forge-${jei_version},)"
   ordering="NONE"
   side="BOTH"
[[dependencies.mineworld]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.mineworld]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"